---
name: Manual - Deploy/Destroy Environment
run-name: Manual ${{ github.event.inputs.actionSelection }} On ${{ github.event.inputs.environment }} Using ${{ github.event.inputs.releaseRef }}

on:
  workflow_dispatch:
    inputs:
      actionSelection:
        type: choice
        required: true
        description: "Action to Perform"
        options:
          - Deploy
          - Destroy
      environment:
        type: choice
        required: true
        description: "Deployment Environment"
        options:
          - prod
          - test
      releaseRef:
        type: string
        default: main
        description: "Git Ref (Branch/Tag) Checked Out During Execution"

jobs:
  deploy:
    name: Manual Deploy
    if: ${{ github.event.inputs.actionSelection == 'Deploy'}}
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-apply-and-deploy-app-via-awx.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      awx-resource-creation-script: create-awx-{{cookiecutter.project_slug}}-deployment-resources.yaml
      awx-deploy-template-name: {{ (cookiecutter.project_name ~ " (Containerized) - Deploy") | urlencode }}
      ref: ${{ github.event.inputs.releaseRef }}
    secrets:
      VAULT_URL: {% raw %}${{github.event.inputs.environment == 'test' ? secrets.VAULT_URL_TEST : secrets.VAULT_URL }}{% endraw %}
      VAULT_TOKEN: {% raw %}${{{github.event.inputs.environment == 'test' ? secrets.VAULT_TOKEN_TEST : secrets.VAULT_TOKEN }}{% endraw %}

  destroy:
    name: Manual Destroy
    if: ${{ github.event.inputs.actionSelection == 'Destroy'}}
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-destroy-and-app-cleanup-via-awx.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      awx-resource-deletion-script: delete-awx-{{cookiecutter.project_slug}}-deployment-resources.yaml
      awx-undeploy-template-name: {{ (cookiecutter.project_name ~ " (Containerized) - Remove") | urlencode }}
      ref: ${{ github.event.inputs.releaseRef }}
    secrets:
      VAULT_URL: {% raw %}${{github.event.inputs.environment == 'test' ? secrets.VAULT_URL_TEST : secrets.VAULT_URL }}{% endraw %}
      VAULT_TOKEN: {% raw %}${{{github.event.inputs.environment == 'test' ? secrets.VAULT_TOKEN_TEST : secrets.VAULT_TOKEN }}{% endraw %}
