---
name: New Release - Deploy To Prod
run-name: Production Deployment for Push on {% raw %}${{ github.ref_name }}{% endraw %}

on:
  workflow_run:
    workflows: ["Push To Main - Release"]
    types:
      - completed

permissions:
  contents: read

jobs:
  get-latest-tag:
    name: Get Latest Tag
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/github-get-latest-repo-tag.yaml@main

  deploy-to-prod:
    name: Deploy To Prod
    needs: get-latest-tag
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-apply-and-deploy-app-via-awx.yaml@main
    with:
      environment: prod
      awx-resource-creation-script: create-awx-{{cookiecutter.project_slug}}-deployment-resources.yaml
      awx-deploy-template-name: {{ (cookiecutter.project_name ~ " (Containerized) - Deploy") | urlencode }}
      ref: {% raw %}${{ needs.get-latest-tag.outputs.latest-tag }}{% endraw %}
    secrets:
      VAULT_URL: {% raw %}${{secrets.VAULT_URL }}{% endraw %}
      VAULT_TOKEN: {% raw %}${{secrets.VAULT_TOKEN }}{% endraw %}
