---
name: New Release - Deploy To Prod
run-name: Production Deployment for Push on {% raw %}${{ github.ref_name }}{% endraw %}

on:
  workflow_run:
    workflows: ["Push To Main - Release"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-to-prod:
    name: Deploy To Prod
    needs: get-latest-tag
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-apply-and-deploy-app-via-awx.yaml@main
    with:
      environment: prod
      awx-resource-creation-script: create-awx-{{cookiecutter.project_slug}}-deployment-resources.yaml
      awx-deploy-template-name: {{ (cookiecutter.project_name ~ " (Containerized) - Deploy") | urlencode }}
    secrets:
      VAULT_URL: {% raw %}${{secrets.VAULT_URL_PROD}}{% endraw %}
      VAULT_TOKEN: {% raw %}${{secrets.VAULT_TOKEN_PROD}}{% endraw %}
